<?xml version="1.0" encoding="utf-8"?><Database Class="CustomersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\v11.0;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="Comment" Member="Comment" Storage="_Comment" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>